#!/bin/sh
#
# @name Gazebo x500 scanner (left/right cameras + optical flow, warehouse inventory)
#
# @type Quadrotor
#
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_scanner}
. ${R}etc/init.d-posix/airframes/4001_gz_x500
